import { PolarCore } from "../core.js";
import { RequestOptions } from "../lib/sdks.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/httpclienterrors.js";
import { OrderNotEligibleForRetry } from "../models/errors/ordernoteligibleforretry.js";
import { PaymentAlreadyInProgress } from "../models/errors/paymentalreadyinprogress.js";
import { PolarError } from "../models/errors/polarerror.js";
import { ResourceNotFound } from "../models/errors/resourcenotfound.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { CustomerPortalOrdersRetryPaymentRequest, CustomerPortalOrdersRetryPaymentSecurity } from "../models/operations/customerportalordersretrypayment.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";
/**
 * Retry Payment
 *
 * @remarks
 * Manually retry payment for a failed order.
 *
 * **Scopes**: `customer_portal:write`
 */
export declare function customerPortalOrdersRetryPayment(client: PolarCore, security: CustomerPortalOrdersRetryPaymentSecurity, request: CustomerPortalOrdersRetryPaymentRequest, options?: RequestOptions): APIPromise<Result<any, ResourceNotFound | PaymentAlreadyInProgress | OrderNotEligibleForRetry | PolarError | ResponseValidationError | ConnectionError | RequestAbortedError | RequestTimeoutError | InvalidRequestError | UnexpectedClientError | SDKValidationError>>;
//# sourceMappingURL=customerPortalOrdersRetryPayment.d.ts.map